### PR TITLE
feat: allow extending log.conf

### PR DESCRIPTION
**Pull request by Va1**
as described in https://github.com/questdb/questdb-kubernetes/issues/80, allows extending log.conf configuration file.

### CODE REVIEW

**Review by bluestreak01 — DISMISSED** [review]

**Comment by Va1** [comment]
@bluestreak01 resolved conflicts which appeared after the other PR got merged

**Comment by sklarsa** [comment]
LGTM, as long as we bump the version accordingly to reflect the potentially breaking change of `config` -> `serverConfig`

**Review by sklarsa — APPROVED** [review]

**Comment by sklarsa** [comment]
Apologies for the delay.. merging now and will create a new release shortly

**Comment by Va1** [comment]
@sklarsa cheers!

**Comment by Va1** [comment]
@sklarsa i see these changes are about to be in 0.21.0, but this version is not yet available. is there anything i can help with to make this happen?

**Comment by sklarsa** [comment]
@Va1 sorry about that! This is the first time that I'm publishing a new version of this package.  I just merged another PR that should make the new version available.  Please let me know if this fixes the issue.

**Comment by Va1** [comment]
@sklarsa the version is out there and i was able to install it, thank you!

**Pull request merged**
